# Generated by Django 5.0.3 on 2024-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zink_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('user_bio', models.TextField()),
                ('user_link', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
