# Generated by Django 5.0.3 on 2024-06-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zink_user',
            old_name='user_bio',
            new_name='profile_bio',
        ),
        migrations.RenameField(
            model_name='zink_user',
            old_name='user_image',
            new_name='profile_img',
        ),
        migrations.RenameField(
            model_name='zink_user',
            old_name='user_link',
            new_name='profile_link',
        ),
    ]
