# Generated by Django 5.0.3 on 2024-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_img',
            new_name='post',
        ),
    ]
